import numpy as np
a=np.array([9,5,1,4,6,2,7,3,5]).reshape(3,3)
b=np.array([1,6,8,4,11,16,9,5,14,10,15,2,13,3,12,7]).reshape(4,4)
print("Pierwsza tablica: ")
print(a)
print("Najmniejsze wartosci kazdego rzedu: ")
print(a.min(axis=1))
print("Najmniejsza wartosc kazdej kolumy: ")
print(a.min(axis=0))
print("Druga tablica: ")
print(b)
print("Najmniejsze wartosci kazdego rzedu: ")
print(b.min(axis=1))
print("Najmniejsza wartosc kazdej kolumy: ")
print(b.min(axis=0))