from zadanie12.art import*
from zadanie12.geo import*
print('Wybierz: ')
print ('ciag arytmetyczny - 0, ciag geometryczny - 1')
wybor=input()
wybor=int(wybor)
if wybor==0:
    print('wzor na n-ty wyraz - 2')
    print('wzor na sume n pierwszych wyrazow ciagu - 3 ')
    liczba=input()
    liczba=int(liczba)
    if liczba==2:
        a=input('pierwszy wyraz: ')
        a=int(a)
        n=input('wyraz,ktory chcesz obliczyc: ')
        n=int(n)
        r=input('ile wynosi roznica: ')
        r=int(r)
        art1(a,n,r)
        print(art1(a,n,r))
    if liczba==3:
        a1=input('pierwszy wyraz ciagu: ')
        a1=float(a1)
        a2=input('ostatni wyraz ciagu: ')
        a2=float(a2)
        n=input('ilosc wyrazow w ciagu : ')
        n=float(n)
        art2(a1,a2,n)
        print(art2(a1,a2,n))
if wybor==2:
    print('wzor na n-ty wyraz - 2 ')
    print('wzor na sume n wyrazow ciagu - 3')
    liczba=input()
    liczba=int(liczba)
    if liczba==2:
        a=input(' pierwszy wyraz ciagu : ')
        a=int(a)
        q=input('iloraz ciagu: ')
        q=int(q)
        n=input('ktory wyraz chcesz obliczyc: ')
        n=int(n)
        geo1(a,q,n)
        print(geo1(a,q,n))
    if liczba==3:
        a=input('pierwszy wyraz ciagu: ')
        a=float(a)
        q=input('iloraz tego ciagu: ')
        q=float(q)
        n=input('ile wyrazow w ciagu: ')
        n=float(n)
        geo2(a,q,n)
        print(geo2(a,q,n))